[package]
name = "pumpkin-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
[dependencies]
pumpkin-util.workspace = true
tokio = { workspace = true, features = ["sync"] }
thiserror.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
# Validate correctness
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
