use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

#[allow(clippy::too_many_lines)]
fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let pumpkin_dir = Path::new(&manifest_dir).join("../assets/translations/pumpkin");

    // Collect all pumpkin .json files for locale code generation
    let mut pumpkin_files: Vec<String> = Vec::new();
    for entry in fs::read_dir(&pumpkin_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "json") {
            pumpkin_files.push(path.file_name().unwrap().to_str().unwrap().to_string());
        }
    }
    pumpkin_files.sort();

    // Generate locale_codes.rs: maps locale index → lowercase underscore code.
    // Uses explicit Locale::Variant references so ordering is always correct
    // regardless of how filenames sort alphabetically.
    let dest_locale_codes = Path::new(&out_dir).join("generated_locale_codes.rs");
    let mut codes_code = String::new();
    codes_code.push_str("// AUTO-GENERATED by pumpkin-i18n build.rs - DO NOT EDIT\n\n");
    codes_code.push_str("#[allow(clippy::missing_const_for_fn, clippy::too_many_lines)]\n");
    codes_code.push_str("pub(crate) fn locale_code(idx: usize) -> &'static str {\n");
    codes_code.push_str("    match idx {\n");
    for file in &pumpkin_files {
        let stem = file.strip_suffix(".json").unwrap();
        let variant = filename_to_variant(stem);
        let _ = writeln!(
            codes_code,
            "        idx if idx == crate::Locale::{variant} as usize => \"{stem}\","
        );
    }
    codes_code.push_str("        _ => \"en_us\",\n");
    codes_code.push_str("    }\n");
    codes_code.push_str("}\n");
    fs::write(&dest_locale_codes, codes_code).unwrap();

    // Generate generated_store.rs: embed ONLY English translations
    let dest_path = Path::new(&out_dir).join("generated_store.rs");
    let mut code = String::new();

    code.push_str("// AUTO-GENERATED by pumpkin-i18n build.rs - DO NOT EDIT\n\n");
    code.push_str("// Only English (en_us) translations are embedded at compile time.\n");
    code.push_str("// Other locales are downloaded at runtime from the configured mirror.\n\n");

    code.push_str("#[allow(clippy::too_many_lines)]\n");
    code.push_str(
        "pub(crate) fn load_all_translations() -> [std::collections::HashMap<String, String>; crate::Locale::COUNT] {\n",
    );
    code.push_str(
        "    let mut array: [std::collections::HashMap<String, String>; crate::Locale::COUNT] = std::array::from_fn(|_| std::collections::HashMap::new());\n\n",
    );

    // Emit pumpkin en_us into EnUs locale with "pumpkin:" prefix
    code.push_str("    // Pumpkin en_us (embedded)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let pumpkin: std::collections::HashMap<String, String> = serde_json::from_str(\n",
    );
    code.push_str(
        "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/pumpkin/en_us.json\"))\n",
    );
    code.push_str("        ).expect(\"Could not parse pumpkin en_us.json\");\n");
    code.push_str("        for (key, value) in pumpkin {\n");
    code.push_str(
        "            array[crate::Locale::EnUs as usize].insert(format!(\"pumpkin:{key}\"), value);\n",
    );
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Emit vanilla en_us_java.json into EnUs locale with "java_minecraft:" prefix
    code.push_str("    // Vanilla Java en_us (embedded)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let vanilla: std::collections::HashMap<String, String> = serde_json::from_str(\n",
    );
    code.push_str(
        "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/vanilla/en_us_java.json\"))\n",
    );
    code.push_str("        ).expect(\"Could not parse en_us_java.json\");\n");
    code.push_str("        for (key, value) in vanilla {\n");
    code.push_str(
        "            array[crate::Locale::EnUs as usize].insert(format!(\"java_minecraft:{key}\"), value);\n",
    );
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Emit vanilla en_us_bedrock.lang into EnUs locale with "bedrock_minecraft:" prefix
    code.push_str("    // Vanilla Bedrock en_us (embedded)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let bedrock: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/vanilla/en_us_bedrock.lang\"));\n",
    );
    code.push_str("        for line in bedrock.lines() {\n");
    code.push_str("            let trimmed = line.trim();\n");
    code.push_str("            if trimmed.is_empty() {\n");
    code.push_str("                continue;\n");
    code.push_str("            }\n");
    code.push_str("            if let Some((key, value)) = trimmed.split_once('=') {\n");
    code.push_str(
        "                array[crate::Locale::EnUs as usize].insert(format!(\"bedrock_minecraft:{}\", key.trim().to_ascii_lowercase()), value.trim().to_string());\n",
    );
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    array\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();

    // Rebuild tracking
    println!("cargo::rerun-if-changed=../assets/translations/pumpkin/");
    println!("cargo::rerun-if-changed=../assets/translations/vanilla/");
}

/// Converts a lowercase underscore-delimited filename stem to a Locale variant name.
/// e.g. `` `af_za` `` -> `` `AfZa` ``, `bar` -> `Bar`, `` `zlm_arab` `` -> `` `ZlmArab` ``
fn filename_to_variant(stem: &str) -> String {
    stem.split('_')
        .map(|part| {
            let mut chars = part.chars();
            chars.next().map_or_else(String::new, |first| {
                first
                    .to_uppercase()
                    .chain(chars.flat_map(char::to_lowercase))
                    .collect()
            })
        })
        .collect()
}
