use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    // Generate generated_store.rs: embed ONLY English translations
    let dest_path = Path::new(&out_dir).join("generated_store.rs");
    let mut code = String::new();

    code.push_str("// AUTO-GENERATED by pumpkin-i18n build.rs - DO NOT EDIT\n\n");
    code.push_str("// Only English (en_us) translations are embedded at compile time.\n");
    code.push_str("// Other locales are downloaded at runtime from the configured mirror.\n\n");

    code.push_str("#[allow(clippy::too_many_lines)]\n");
    code.push_str(
        "pub(crate) fn load_all_translations() -> [std::collections::HashMap<String, String>; crate::Locale::COUNT] {\n",
    );
    code.push_str(
        "    let mut array: [std::collections::HashMap<String, String>; crate::Locale::COUNT] = std::array::from_fn(|_| std::collections::HashMap::new());\n\n",
    );

    // Emit pumpkin en_us into EnUs locale with "pumpkin:" prefix
    code.push_str("    // Pumpkin en_us (embedded)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let pumpkin: std::collections::HashMap<String, String> = serde_json::from_str(\n",
    );
    code.push_str(
        "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/pumpkin/en_us.json\"))\n",
    );
    code.push_str("        ).expect(\"Could not parse pumpkin en_us.json\");\n");
    code.push_str("        for (key, value) in pumpkin {\n");
    code.push_str(
        "            array[crate::Locale::EnUs as usize].insert(format!(\"pumpkin:{key}\"), value);\n",
    );
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Emit vanilla en_us_java.json into EnUs locale with "java_minecraft:" prefix
    code.push_str("    // Vanilla Java en_us (embedded)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let vanilla: std::collections::HashMap<String, String> = serde_json::from_str(\n",
    );
    code.push_str(
        "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/vanilla/en_us_java.json\"))\n",
    );
    code.push_str("        ).expect(\"Could not parse en_us_java.json\");\n");
    code.push_str("        for (key, value) in vanilla {\n");
    code.push_str(
        "            array[crate::Locale::EnUs as usize].insert(format!(\"java_minecraft:{key}\"), value);\n",
    );
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Emit vanilla en_us_bedrock.lang into EnUs locale with "bedrock_minecraft:" prefix
    code.push_str("    // Vanilla Bedrock en_us (embedded)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let bedrock: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/vanilla/en_us_bedrock.lang\"));\n",
    );
    code.push_str("        for line in bedrock.lines() {\n");
    code.push_str("            let trimmed = line.trim();\n");
    code.push_str("            if trimmed.is_empty() {\n");
    code.push_str("                continue;\n");
    code.push_str("            }\n");
    code.push_str("            if let Some((key, value)) = trimmed.split_once('=') {\n");
    code.push_str(
        "                array[crate::Locale::EnUs as usize].insert(format!(\"bedrock_minecraft:{}\", key.trim().to_ascii_lowercase()), value.trim().replace(\"%%\", \"%\"));\n",
    );
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    array\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();

    // Rebuild tracking
    println!("cargo::rerun-if-changed=../assets/translations/pumpkin/");
    println!("cargo::rerun-if-changed=../assets/translations/vanilla/");
}
