[package]
name = "pumpkin-nbt"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
bytes.workspace = true

cesu8 = "1.1"
flate2 = "1.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tempfile = "3.19"
