[package]
name = "pumpkin-nbt"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
bytes.workspace = true

cesu8 = "1.1"

[dev-dependencies]
flate2 = "1.0"
fastnbt = { git = "https://github.com/owengage/fastnbt.git" }
