use heck::{ToPascalCase, ToSnakeCase};
use std::{collections::HashSet, fs, path::Path};
use syn::{Attribute, Fields, Item};

pub fn build_java_mapping() -> String {
    let mut output = String::new();
    output.push_str("// Generated by pumpkin-codegen. Do not edit.\n");
    output.push_str("#![allow(clippy::all)]\n");
    output.push_str("#![allow(clippy::pedantic)]\n");
    output.push_str("#![allow(unused_imports)]\n");
    output.push_str("#![allow(unused_variables)]\n");
    output.push_str("use crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::java_packets::{ClientboundPacket, ServerboundPacket};\n");
    output.push_str("use pumpkin_protocol::codec::var_int::VarInt;\n");
    output.push_str("use pumpkin_util::version::JavaMinecraftVersion;\n");
    output.push_str("use bytes::Bytes;\n");
    output.push_str("use std::io::Cursor;\n");
    output.push_str("use std::any::Any;\n");
    output.push_str("use pumpkin_protocol::packet::MultiVersionJavaPacket;\n");
    output.push_str("use pumpkin_protocol::packet::Packet;\n\n");
    output.push_str("use pumpkin_protocol::ConnectionState;\n\n");

    output.push_str("#[must_use]\n");
    output.push_str("pub fn serialize_java_packet(packet: &ClientboundPacket, version: JavaMinecraftVersion) -> Option<Bytes> {\n");
    output.push_str(
        "    serialize_java_packet_with_state(packet, version).map(|(_, bytes)| bytes)\n}\n\n",
    );
    output.push_str("pub fn serialize_java_packet_with_state(packet: &ClientboundPacket, version: JavaMinecraftVersion) -> Option<(ConnectionState, Bytes)> {\n");
    output.push_str("    serialize_java_clientbound_packet_inner(packet, None, version)\n}\n\n");
    output.push_str("pub fn serialize_java_clientbound_packet(packet: &ClientboundPacket, state: ConnectionState, version: JavaMinecraftVersion) -> Option<Bytes> {\n");
    output.push_str(
        "    serialize_java_clientbound_packet_inner(packet, Some(state), version).map(|(_, bytes)| bytes)\n}\n\n",
    );
    output.push_str("fn serialize_java_clientbound_packet_inner(packet: &ClientboundPacket, state: Option<ConnectionState>, version: JavaMinecraftVersion) -> Option<(ConnectionState, Bytes)> {\n");
    output.push_str("    match packet {\n");

    let client_states = &["config", "login", "play", "status"];
    let server_states = &["config", "handshake", "login", "play", "status"];

    for state in client_states {
        process_packets(
            &format!("../../crates/pumpkin-protocol/src/java/client/{}", state),
            state,
            &mut output,
            "java_packet",
            "ClientboundPacket",
            &format!("pumpkin_protocol::java::client::{}", state),
            false,
            MappingMode::Serialize,
        );
    }

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("pub fn serialize_java_serverbound_packet(packet: &ServerboundPacket, state: ConnectionState, version: JavaMinecraftVersion) -> Option<Bytes> {\n");
    output.push_str("    let state = Some(state);\n    match packet {\n");
    for state in server_states {
        process_packets(
            &format!("../../crates/pumpkin-protocol/src/java/server/{}", state),
            state,
            &mut output,
            "java_packet",
            "ServerboundPacket",
            &format!("pumpkin_protocol::java::server::{}", state),
            false,
            MappingMode::Serialize,
        );
    }

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    for (direction, states, packet_type) in [
        ("server", server_states.as_slice(), "ServerboundPacket"),
        ("client", client_states.as_slice(), "ClientboundPacket"),
    ] {
        output.push_str(&format!("pub fn deserialize_java_{}bound_packet(state: ConnectionState, id: i32, mut payload: &[u8], version: JavaMinecraftVersion) -> Option<{}> {{\n", direction, packet_type));
        output.push_str("    if id < 0 { return None; }\n    match state {\n");
        for state in states {
            output.push_str(&format!(
                "        {} => match id {{\n",
                java_state_pattern(state)
            ));
            process_packets(
                &format!("../../crates/pumpkin-protocol/src/java/{direction}/{state}"),
                state,
                &mut output,
                "java_packet",
                packet_type,
                &format!("pumpkin_protocol::java::{direction}::{state}"),
                false,
                MappingMode::Deserialize,
            );
            output.push_str("            _ => None,\n        },\n");
        }
        if direction == "client" {
            output.push_str("        ConnectionState::HandShake => None,\n");
        }
        output.push_str("    }\n}\n\n");
    }

    output.push_str("pub trait ToWitClientboundJava {\n");
    output.push_str("    fn to_wit(&self) -> ClientboundPacket;\n");
    output.push_str("}\n\n");

    for state in client_states {
        process_packets(
            &format!("../../crates/pumpkin-protocol/src/java/client/{}", state),
            state,
            &mut output,
            "java_packet",
            "ClientboundPacket",
            &format!("pumpkin_protocol::java::client::{}", state),
            false,
            MappingMode::ToWit,
        );
    }

    output.push_str("#[must_use]\n");
    output.push_str(
        "pub fn clientbound_java_any_to_wit(any: &dyn Any) -> Option<ClientboundPacket> {\n",
    );
    for state in client_states {
        process_packets(
            &format!("../../crates/pumpkin-protocol/src/java/client/{}", state),
            state,
            &mut output,
            "java_packet",
            "ClientboundPacket",
            &format!("pumpkin_protocol::java::client::{}", state),
            false,
            MappingMode::Downcast,
        );
    }
    output.push_str("    None\n");
    output.push_str("}\n\n");

    output.push_str(JAVA_CODEC_TESTS);
    output
}

const JAVA_CODEC_TESTS: &str = r#"
#[cfg(test)]
mod java_codec_tests {
    use super::*;
    use pumpkin_protocol::{ClientPacket, ser::NetworkReadExt};
    use pumpkin_util::text::TextComponent;

    fn split_packet(bytes: &[u8]) -> (i32, &[u8]) {
        let mut payload = bytes;
        let id = payload.get_var_int().unwrap().0;
        (id, payload)
    }

    #[test]
    fn packet_codecs_preserve_phase_and_roundtrip_values() {
        let version = JavaMinecraftVersion::V_1_21_11;
        let request = ServerboundPacket::StatusSStatusRequest;
        let encoded = serialize_java_serverbound_packet(&request, ConnectionState::Status, version).unwrap();
        let (id, payload) = split_packet(&encoded);
        assert!(matches!(deserialize_java_serverbound_packet(ConnectionState::Status, id, payload, version), Some(ServerboundPacket::StatusSStatusRequest)));
        assert!(deserialize_java_serverbound_packet(ConnectionState::Login, id, payload, version).is_none());
        assert!(serialize_java_serverbound_packet(&request, ConnectionState::Play, version).is_none());

        let packet = pumpkin_protocol::java::server::handshake::SHandShake {
            protocol_version: VarInt(version.protocol_version()),
            server_address: "localhost".into(),
            server_port: 25565,
            next_state: ConnectionState::Login,
        };
        let encoded = packet.serialize_packet(&version).unwrap();
        let (id, payload) = split_packet(&encoded);
        let mut decoded = deserialize_java_serverbound_packet(ConnectionState::HandShake, id, payload, version).unwrap();
        assert_eq!(serialize_java_serverbound_packet(&decoded, ConnectionState::HandShake, version).unwrap(), encoded);
        if let ServerboundPacket::HandshakeSHandShake(data) = &mut decoded {
            data.server_port = 65536;
        } else {
            panic!("unexpected handshake wrapper");
        }
        assert!(serialize_java_serverbound_packet(&decoded, ConnectionState::HandShake, version).is_none());

        let uuid = uuid::Uuid::from_u64_pair(0x123456789abcdef0, 0x0fedcba987654321);
        let login = pumpkin_protocol::java::server::login::SLoginStart { name: "tester".into(), uuid };
        let encoded = login.serialize_packet(&version).unwrap();
        let (id, payload) = split_packet(&encoded);
        let decoded = deserialize_java_serverbound_packet(ConnectionState::Login, id, payload, version).unwrap();
        assert_eq!(serialize_java_serverbound_packet(&decoded, ConnectionState::Login, version).unwrap(), encoded);

        let response = pumpkin_protocol::java::client::status::CStatusResponse { json_response: "{}".into() };
        let encoded = response.serialize_packet(&version).unwrap();
        let (id, payload) = split_packet(&encoded);
        assert!(matches!(deserialize_java_clientbound_packet(ConnectionState::Status, id, payload, version), Some(ClientboundPacket::StatusCStatusResponse(_))));
        assert!(matches!(deserialize_java_clientbound_packet(ConnectionState::Login, id, payload, version), Some(ClientboundPacket::LoginCLoginDisconnect(_))));
        assert!(deserialize_java_clientbound_packet(ConnectionState::Status, -1, payload, version).is_none());

        let content = TextComponent::text("packet text");
        let chat = pumpkin_protocol::java::client::play::CSystemChatMessage::new(&content, false);
        let mut wrapper = chat.to_wit();
        assert_eq!(serialize_java_packet(&wrapper, version).unwrap(), chat.serialize_packet(&version).unwrap());
        if let ClientboundPacket::CSystemChatMessage(data) = &mut wrapper {
            data.content = "{".into();
        }
        assert!(serialize_java_packet(&wrapper, version).is_none());

        let (state, _) = serialize_java_packet_with_state(&ClientboundPacket::CStartConfiguration, version).unwrap();
        assert_eq!(state, ConnectionState::Play);
        let (state, _) = serialize_java_packet_with_state(&ClientboundPacket::ConfigCFinishConfig, version).unwrap();
        assert_eq!(state, ConnectionState::Config);
    }

    #[test]
    fn bedrock_packet_replacement_roundtrip() {
        use crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::bedrock_packets;
        let packet = BServerboundPacket::SContainerClose(bedrock_packets::SContainerClose {
            container_id: 7,
            container_type: 1,
            server_initiated_close: false,
        });
        let bytes = serialize_bedrock_serverbound_packet(&packet).unwrap();
        assert_eq!(bytes.as_ref(), &[47, 7, 1, 0]);
        assert!(matches!(deserialize_bedrock_serverbound_packet(47, &bytes[1..]), Some(BServerboundPacket::SContainerClose(_))));
        assert!(serialize_bedrock_serverbound_packet(&BServerboundPacket::Unknown).is_none());
    }
}
"#;

pub fn build_bedrock_mapping() -> String {
    let mut output = String::new();
    output.push_str("\nuse crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::bedrock_packets::{ClientboundPacket as BClientboundPacket, ServerboundPacket as BServerboundPacket};\n\n");
    output.push_str("#[must_use]\n");
    output.push_str(
        "pub fn serialize_bedrock_packet(packet: &BClientboundPacket) -> Option<Bytes> {\n",
    );
    output.push_str("    match packet {\n");

    process_packets(
        "../../crates/pumpkin-protocol/src/bedrock/client",
        "",
        &mut output,
        "packet",
        "BClientboundPacket",
        "pumpkin_protocol::bedrock::client",
        true,
        MappingMode::Serialize,
    );

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("pub fn serialize_bedrock_serverbound_packet(packet: &BServerboundPacket) -> Option<Bytes> {\n    match packet {\n");
    process_packets(
        "../../crates/pumpkin-protocol/src/bedrock/server",
        "",
        &mut output,
        "packet",
        "BServerboundPacket",
        "pumpkin_protocol::bedrock::server",
        true,
        MappingMode::Serialize,
    );
    output.push_str("        _ => None,\n    }\n}\n\n");

    output.push_str("#[must_use]\n");
    output.push_str("pub fn deserialize_bedrock_serverbound_packet(id: i32, payload: &[u8]) -> Option<BServerboundPacket> {\n");
    output.push_str("    match id {\n");

    process_packets(
        "../../crates/pumpkin-protocol/src/bedrock/server",
        "",
        &mut output,
        "packet",
        "BServerboundPacket",
        "pumpkin_protocol::bedrock::server",
        true,
        MappingMode::Deserialize,
    );

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("pub trait ToWitClientboundBedrock {\n");
    output.push_str("    fn to_wit(&self) -> BClientboundPacket;\n");
    output.push_str("}\n\n");

    process_packets(
        "../../crates/pumpkin-protocol/src/bedrock/client",
        "",
        &mut output,
        "packet",
        "BClientboundPacket",
        "pumpkin_protocol::bedrock::client",
        true,
        MappingMode::ToWit,
    );

    output.push_str("#[must_use]\n");
    output.push_str(
        "pub fn clientbound_bedrock_any_to_wit(any: &dyn Any) -> Option<BClientboundPacket> {\n",
    );
    process_packets(
        "../../crates/pumpkin-protocol/src/bedrock/client",
        "",
        &mut output,
        "packet",
        "BClientboundPacket",
        "pumpkin_protocol::bedrock::client",
        true,
        MappingMode::Downcast,
    );
    output.push_str("    None\n");
    output.push_str("}\n\n");

    output
}

#[derive(Clone, Copy, PartialEq)]
enum MappingMode {
    Serialize,
    Deserialize,
    ToWit,
    Downcast,
}

fn has_attr(attrs: &[Attribute], attr_name: &str) -> bool {
    attrs.iter().any(|attr| attr.path().is_ident(attr_name))
}

fn derives_trait(attrs: &[Attribute], trait_name: &str) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("derive")
            && attr
                .parse_args_with(
                    syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
                )
                .is_ok_and(|paths| paths.iter().any(|path| path.is_ident(trait_name)))
    })
}

pub(super) fn implemented_types(file: &syn::File, trait_name: &str) -> HashSet<String> {
    file.items
        .iter()
        .filter_map(|item| {
            let Item::Impl(item) = item else { return None };
            let (path, _) = item.trait_.as_ref()?;
            if path.segments.last()?.ident != trait_name {
                return None;
            }
            let syn::Type::Path(ty) = item.self_ty.as_ref() else {
                return None;
            };
            Some(ty.path.segments.last()?.ident.to_string())
        })
        .collect()
}

fn java_state_pattern(state: &str) -> &'static str {
    match state {
        "handshake" => "ConnectionState::HandShake",
        "status" => "ConnectionState::Status",
        "login" => "ConnectionState::Login | ConnectionState::Transfer",
        "config" => "ConnectionState::Config",
        "play" => "ConnectionState::Play",
        _ => unreachable!(),
    }
}

fn serialization_guard(state: &str, attr_name: &str) -> String {
    if attr_name == "java_packet" {
        format!(
            " if state.is_none_or(|state| matches!(state, {}))",
            java_state_pattern(state)
        )
    } else {
        String::new()
    }
}

fn get_type_info(ty: &syn::Type) -> (String, bool, bool) {
    match ty {
        syn::Type::Path(tp) => {
            let segment = tp.path.segments.last().unwrap();
            if segment.ident == "Box"
                && let syn::PathArguments::AngleBracketed(args) = &segment.arguments
                && let Some(syn::GenericArgument::Type(syn::Type::Slice(slice))) = args.args.first()
                && let syn::Type::Path(inner) = &*slice.elem
                && inner
                    .path
                    .segments
                    .last()
                    .is_some_and(|segment| segment.ident == "u8")
            {
                return ("BoxedU8Slice".to_string(), false, false);
            }
            if segment.ident == "Box"
                && let syn::PathArguments::AngleBracketed(args) = &segment.arguments
                && let Some(syn::GenericArgument::Type(syn::Type::Path(inner))) = args.args.first()
                && inner.path.is_ident("str")
            {
                return ("BoxedStr".to_string(), false, false);
            }
            if segment.ident == "Vec"
                && let syn::PathArguments::AngleBracketed(args) = &segment.arguments
                && let Some(syn::GenericArgument::Type(syn::Type::Path(inner))) = args.args.first()
                && inner.path.is_ident("u8")
            {
                return ("ByteVec".to_string(), false, false);
            }
            if segment.ident == "Option"
                && let syn::PathArguments::AngleBracketed(args) = &segment.arguments
                && let Some(syn::GenericArgument::Type(inner)) = args.args.first()
            {
                let (name, is_ref, is_slice) = get_type_info(inner);
                if name == "u8" && is_ref && is_slice {
                    return ("OptionalByteSlice".to_string(), false, false);
                }
                if !is_ref && !is_slice {
                    return (format!("Optional{name}"), false, false);
                }
            }
            (segment.ident.to_string(), false, false)
        }
        syn::Type::Reference(tr) => {
            let (name, _, is_slice) = get_type_info(&tr.elem);
            (name, true, is_slice)
        }
        syn::Type::Slice(ts) => {
            let (name, _, _) = get_type_info(&ts.elem);
            (name, false, true)
        }
        _ => (String::new(), false, false),
    }
}

/// Generates the conversion of a value according to its type.
/// `src` is the source expression (ex: "data.field", "self.field", "identifier")
/// `dst` is the destination name (ex: "field_name", "wit_field") — None for unnamed (we just return the expression)
/// Returns (prep_code, converted_expression, possible)
fn convert_value(
    type_ident: &str,
    is_ref: bool,
    is_slice: bool,
    src: &str,
    dst: Option<&str>,
    mode: MappingMode,
    prep_prefix: &str, // indentation for prefix
) -> (String, String, bool) {
    let mut prep = String::new();
    let mut possible = true;

    let expr = match type_ident {
        "OptionalBoxedU8Slice" | "OptionalByteSlice" | "OptionalBytes" | "OptionalByteVec" => {
            match mode {
                MappingMode::Serialize => match type_ident {
                    "OptionalBoxedU8Slice" => format!(
                        "{}.as_ref().map(|bytes| bytes.clone().into_boxed_slice())",
                        src
                    ),
                    "OptionalByteSlice" => format!("{}.as_deref()", src),
                    _ => format!("{}.as_ref().map(|bytes| bytes.clone().into())", src),
                },
                MappingMode::Deserialize | MappingMode::ToWit => {
                    format!("{}.as_ref().map(|bytes| bytes.to_vec())", src)
                }
                MappingMode::Downcast => String::new(),
            }
        }
        "OptionalUuid" => match mode {
            MappingMode::Serialize => format!(
                "{}.as_ref().map(|value| uuid::Uuid::from_u64_pair(value.high, value.low))",
                src
            ),
            MappingMode::Deserialize | MappingMode::ToWit => format!(
                "{}.as_ref().map(|value| crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::uuid::Uuid {{ high: value.as_u64_pair().0, low: value.as_u64_pair().1 }})",
                src
            ),
            MappingMode::Downcast => String::new(),
        },
        "OptionalVarInt" => match mode {
            MappingMode::Serialize => format!("{}.map(VarInt)", src),
            MappingMode::Deserialize | MappingMode::ToWit => {
                format!("{}.map(|value| value.0)", src)
            }
            MappingMode::Downcast => String::new(),
        },
        "BoxedStr" => match mode {
            MappingMode::Serialize => format!("{}.clone().into_boxed_str()", src),
            MappingMode::Deserialize | MappingMode::ToWit => format!("{}.to_string()", src),
            MappingMode::Downcast => String::new(),
        },
        "Bytes" | "ByteVec" => match mode {
            MappingMode::Serialize => format!("{}.clone().into()", src),
            MappingMode::Deserialize | MappingMode::ToWit => format!("{}.to_vec()", src),
            MappingMode::Downcast => String::new(),
        },
        "ConnectionState" => match mode {
            MappingMode::Serialize => format!(
                "pumpkin_protocol::ConnectionState::try_from(VarInt({})).ok()?",
                src
            ),
            MappingMode::Deserialize | MappingMode::ToWit => format!("{} as i32", src),
            MappingMode::Downcast => String::new(),
        },
        "String" | "str" => match mode {
            MappingMode::Serialize => {
                if is_slice {
                    let tmp = dst.unwrap_or("slice");
                    if is_ref {
                        prep.push_str(&format!(
                            "{}let vec_{}: Vec<&str> = {}.iter().map(|s| s.as_str()).collect();\n",
                            prep_prefix, tmp, src
                        ));
                        format!("&vec_{}", tmp)
                    } else {
                        format!("{}.clone()", src)
                    }
                } else if is_ref {
                    format!("&{}", src)
                } else {
                    format!("{}.clone()", src)
                }
            }
            MappingMode::Deserialize => {
                if is_slice {
                    format!("{}.iter().map(|s| s.to_string()).collect()", src)
                } else {
                    format!("{}.into()", src)
                }
            }
            MappingMode::ToWit => {
                if is_slice {
                    format!("{}.iter().map(|s| s.to_string()).collect()", src)
                } else {
                    format!("{}.to_string()", src)
                }
            }
            MappingMode::Downcast => String::new(),
        },
        "Identifier" => match mode {
            MappingMode::Serialize => {
                let value = format!(
                    "pumpkin_util::identifier::Identifier::try_from({}.as_str()).ok()?",
                    src
                );
                if is_ref {
                    let tmp = dst.unwrap_or("identifier");
                    prep.push_str(&format!(
                        "{}let identifier_{} = {};\n",
                        prep_prefix, tmp, value
                    ));
                    format!("&identifier_{}", tmp)
                } else {
                    value
                }
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                format!("{}.to_string()", src)
            }
            MappingMode::Downcast => String::new(),
        },
        "VarUInt" => match mode {
            MappingMode::Serialize => {
                format!("pumpkin_protocol::codec::var_uint::VarUInt({} as u32)", src)
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                format!("{}.0 as _", src)
            }
            MappingMode::Downcast => String::new(),
        },
        "VarLong" | "VarULong" => {
            let is_ulong = type_ident == "VarULong";
            let path = if is_ulong {
                "pumpkin_protocol::codec::var_ulong::VarULong"
            } else {
                "pumpkin_protocol::codec::var_long::VarLong"
            };

            if mode == MappingMode::Serialize {
                let tmp = dst.unwrap_or("tmp").replace('.', "_");
                if is_slice {
                    prep.push_str(&format!(
                        "{}let vec_{}: Vec<{}> = {}.iter().map(|v| {}(*v as _)).collect();\n",
                        prep_prefix, tmp, path, src, path
                    ));
                    if is_ref {
                        format!("&vec_{}", tmp)
                    } else {
                        format!("vec_{}", tmp)
                    }
                } else {
                    if is_ref {
                        prep.push_str(&format!(
                            "{}let var_long_{} = {}({} as _);\n",
                            prep_prefix, tmp, path, src
                        ));
                        format!("&var_long_{}", tmp)
                    } else {
                        format!("{}({} as _)", path, src)
                    }
                }
            } else if mode == MappingMode::Deserialize {
                if is_slice {
                    format!("{}.iter().map(|v| v.0 as _).collect()", src)
                } else {
                    format!("{}.0 as _", src)
                }
            } else {
                // ToWit
                if is_slice {
                    format!("{}.iter().map(|v| v.0 as _).collect()", src)
                } else {
                    format!("{}.0 as _", src)
                }
            }
        }
        "TextComponent" => match mode {
            MappingMode::Serialize => {
                let tmp = dst.unwrap_or("tmp").replace('.', "_");
                prep.push_str(&format!(
                    "{}let component_{}: pumpkin_util::text::TextComponent = serde_json::from_str(&{}).ok()?;\n",
                    prep_prefix, tmp, src
                ));
                if is_ref {
                    format!("&component_{}", tmp)
                } else {
                    format!("component_{}", tmp)
                }
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                format!("serde_json::to_string(&{}).unwrap_or_default()", src)
            }
            MappingMode::Downcast => String::new(),
        },

        "BlockPos" => match mode {
            MappingMode::Serialize => {
                format!(
                    "pumpkin_util::math::position::BlockPos::new({}.0, {}.1, {}.2)",
                    src, src, src
                )
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                format!("({}.0.x, {}.0.y, {}.0.z)", src, src, src)
            }
            MappingMode::Downcast => String::new(),
        },

        "Vector3" => match mode {
            MappingMode::Serialize => {
                format!(
                    "pumpkin_util::math::vector3::Vector3::new({}.0 as _, {}.1 as _, {}.2 as _)",
                    src, src, src
                )
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                format!("({}.x as _, {}.y as _, {}.z as _)", src, src, src)
            }
            MappingMode::Downcast => String::new(),
        },

        "LpVector3d" => match mode {
            MappingMode::Serialize => {
                let tmp = dst.unwrap_or("velocity").replace('.', "_");
                prep.push_str(&format!(
                    "{}let parsed_{}: [f64; 3] = serde_json::from_str(&{}).ok()?;\n",
                    prep_prefix, tmp, src
                ));
                format!(
                    "pumpkin_protocol::codec::lp_vector_3d::LpVector3d(pumpkin_util::math::vector3::Vector3::new(parsed_{0}[0], parsed_{0}[1], parsed_{0}[2]))",
                    tmp
                )
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                format!(
                    "serde_json::to_string(&[{}.0.x, {}.0.y, {}.0.z]).unwrap_or_default()",
                    src, src, src
                )
            }
            MappingMode::Downcast => String::new(),
        },

        "BoxedU8Slice" => match mode {
            MappingMode::Serialize => format!("{}.clone().into_boxed_slice()", src),
            MappingMode::Deserialize | MappingMode::ToWit => format!("{}.to_vec()", src),
            MappingMode::Downcast => String::new(),
        },

        "Uuid" => match mode {
            MappingMode::Serialize => {
                let tmp = dst.unwrap_or("tmp").replace('.', "_");
                if is_slice {
                    prep.push_str(&format!(
                        "{}let vec_{} = {}.iter().map(|u| uuid::Uuid::from_u64_pair(u.high, u.low)).collect::<Vec<_>>();\n",
                        prep_prefix, tmp, src
                    ));
                    if is_ref {
                        format!("&vec_{}", tmp)
                    } else {
                        format!("vec_{}", tmp)
                    }
                } else {
                    prep.push_str(&format!(
                        "{}let uuid_{} = uuid::Uuid::from_u64_pair({}.high, {}.low);\n",
                        prep_prefix, tmp, src, src
                    ));
                    if is_ref {
                        format!("&uuid_{}", tmp)
                    } else {
                        format!("uuid_{}", tmp)
                    }
                }
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                let map_fn = format!(
                    "crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::uuid::Uuid {{ high: {{}}.as_u64_pair().0, low: {{}}.as_u64_pair().1 }}",
                );
                if is_slice {
                    format!(
                        "{}.iter().map(|u| {}).collect()",
                        src,
                        map_fn.replace("{}", "u")
                    )
                } else {
                    format!(
                        "crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::uuid::Uuid {{ high: {}.as_u64_pair().0, low: {}.as_u64_pair().1 }}",
                        src, src
                    )
                }
            }
            MappingMode::Downcast => String::new(),
        },

        "i32" | "u32" | "i64" | "u64" | "bool" | "f32" | "f64" | "u8" | "i8" | "u16" | "i16"
        | "VarInt" => match mode {
            MappingMode::Serialize => {
                let tmp = dst.unwrap_or("tmp").replace('.', "_");
                if is_slice {
                    if type_ident == "u8" {
                        if is_ref {
                            format!("&{}", src)
                        } else {
                            format!("{}.clone()", src)
                        }
                    } else if type_ident == "VarInt" {
                        prep.push_str(&format!(
                            "{}let vec_{}: Vec<VarInt> = {}.iter().map(|v| VarInt(*v)).collect();\n",
                            prep_prefix, tmp, src
                        ));
                        if is_ref {
                            format!("&vec_{}", tmp)
                        } else {
                            format!("vec_{}", tmp)
                        }
                    } else if is_ref {
                        prep.push_str(&format!(
                            "{}let vec_{}: Vec<_> = {}.iter().map(|v| *v as _).collect();\n",
                            prep_prefix, tmp, src
                        ));
                        format!("&vec_{}", tmp)
                    } else {
                        format!("{}.iter().map(|v| *v as _).collect()", src)
                    }
                } else if type_ident == "VarInt" {
                    if is_ref {
                        prep.push_str(&format!(
                            "{}let var_int_{} = VarInt({});\n",
                            prep_prefix, tmp, src
                        ));
                        format!("&var_int_{}", tmp)
                    } else {
                        format!("VarInt({})", src)
                    }
                } else {
                    if is_ref {
                        prep.push_str(&format!(
                            "{}let val_{} = {}.try_into().ok()?;\n",
                            prep_prefix, tmp, src
                        ));
                        format!("&val_{}", tmp)
                    } else {
                        if matches!(type_ident, "u32" | "u64" | "i8") {
                            format!("{} as {}", src, type_ident)
                        } else {
                            format!("{}.try_into().ok()?", src)
                        }
                    }
                }
            }
            MappingMode::Deserialize | MappingMode::ToWit => {
                if is_slice {
                    if type_ident == "VarInt" {
                        format!("{}.iter().map(|v| v.0 as _).collect()", src)
                    } else {
                        format!("{}.iter().map(|v| *v as _).collect()", src)
                    }
                } else if type_ident == "VarInt" {
                    format!("{}.0 as _", src)
                } else if type_ident == "bool" {
                    src.to_string()
                } else {
                    format!("{} as _", src)
                }
            }
            MappingMode::Downcast => String::new(),
        },

        _ => {
            possible = false;
            String::new()
        }
    };

    (prep, expr, possible)
}

fn process_packets(
    dir: &str,
    state: &str,
    output: &mut String,
    attr_name: &str,
    variant_prefix: &str,
    rust_path_prefix: &str,
    skip_raknet: bool,
    mode: MappingMode,
) {
    let paths = fs::read_dir(dir).expect("Failed to read packet directory");
    let mut sorted_paths: Vec<_> = paths
        .map(|e| e.expect("Failed to read entry").path())
        .collect();
    sorted_paths.sort();

    for path in sorted_paths {
        if path.is_dir() {
            if skip_raknet && path.file_name().unwrap() == "raknet" {
                continue;
            }
            process_packets(
                path.to_str().unwrap(),
                state,
                output,
                attr_name,
                variant_prefix,
                rust_path_prefix,
                skip_raknet,
                mode,
            );
            continue;
        }
        if path.extension().is_some_and(|ext| ext == "rs")
            && path
                .file_name()
                .is_some_and(|name| name != "mod.rs" || state == "handshake")
        {
            parse_packet_file(
                &path,
                state,
                output,
                attr_name,
                variant_prefix,
                rust_path_prefix,
                mode,
            );
        }
    }
}

fn parse_packet_file(
    path: &Path,
    state: &str,
    output: &mut String,
    attr_name: &str,
    variant_prefix: &str,
    rust_path_prefix: &str,
    mode: MappingMode,
) {
    let content = fs::read_to_string(path).expect("Failed to read file");
    let file = syn::parse_file(&content).expect("Failed to parse file");
    let packet_types = implemented_types(&file, "MultiVersionJavaPacket");
    let readers = implemented_types(&file, "ServerPacket");
    let mut writers = implemented_types(&file, "PacketWrite");
    writers.extend(implemented_types(&file, "BClientPacket"));

    for item in file.items {
        match item {
            Item::Struct(s)
                if has_attr(&s.attrs, attr_name)
                    || attr_name == "java_packet"
                        && packet_types.contains(&s.ident.to_string()) =>
            {
                if s.ident == "CHandshake" {
                    continue;
                }
                if mode == MappingMode::Serialize
                    && variant_prefix == "BServerboundPacket"
                    && !writers.contains(&s.ident.to_string())
                    && !derives_trait(&s.attrs, "PacketWrite")
                {
                    continue;
                }
                if mode == MappingMode::Deserialize
                    && attr_name == "java_packet"
                    && !readers.contains(&s.ident.to_string())
                {
                    continue;
                }
                process_struct(
                    s,
                    state,
                    output,
                    attr_name,
                    variant_prefix,
                    rust_path_prefix,
                    mode,
                );
            }
            Item::Enum(e)
                if has_attr(&e.attrs, attr_name)
                    || attr_name == "java_packet"
                        && packet_types.contains(&e.ident.to_string()) =>
            {
                if mode == MappingMode::Serialize
                    && variant_prefix == "BServerboundPacket"
                    && !writers.contains(&e.ident.to_string())
                    && !derives_trait(&e.attrs, "PacketWrite")
                {
                    continue;
                }
                if mode == MappingMode::Deserialize
                    && attr_name == "java_packet"
                    && !readers.contains(&e.ident.to_string())
                {
                    continue;
                }
                process_enum(
                    e,
                    state,
                    output,
                    attr_name,
                    variant_prefix,
                    rust_path_prefix,
                    mode,
                );
            }
            _ => {}
        }
    }
}

fn process_struct(
    s: syn::ItemStruct,
    state: &str,
    output: &mut String,
    attr_name: &str,
    variant_prefix: &str,
    rust_path_prefix: &str,
    mode: MappingMode,
) {
    let struct_name = s.ident.to_string();
    let wit_case = if state == "play" {
        struct_name.to_pascal_case()
    } else {
        format!("{}{}", state, struct_name).to_pascal_case()
    };
    let struct_name_with_lt = if !s.generics.params.is_empty() {
        format!("{}<'_>", struct_name)
    } else {
        struct_name.clone()
    };

    if attr_name == "java_packet" && matches!(&s.fields, Fields::Unit) {
        let rust_type = format!("{rust_path_prefix}::{struct_name}");
        let variant = format!("{variant_prefix}::{wit_case}");
        match mode {
            MappingMode::Serialize => {
                let with_state = if variant_prefix == "ClientboundPacket" {
                    format!(".map(|bytes| (<{rust_type} as MultiVersionJavaPacket>::state(), bytes))")
                } else { String::new() };
                output.push_str(&format!(
                    "        {variant}{} => pumpkin_protocol::ClientPacket::serialize_packet(&{rust_type}, &version).ok(){with_state},\n",
                    serialization_guard(state, attr_name)
                ));
            }
            MappingMode::Deserialize => output.push_str(&format!(
                "        id if id == {rust_type}::to_id(version) => {{\n            <{rust_type} as pumpkin_protocol::ServerPacket>::read(&mut payload, &version).ok()?;\n            if !payload.is_empty() {{ return None; }}\n            Some({variant})\n        }}\n"
            )),
            MappingMode::ToWit => output.push_str(&format!(
                "impl ToWitClientboundJava for {rust_type} {{\n    fn to_wit(&self) -> ClientboundPacket {{ {variant} }}\n}}\n"
            )),
            MappingMode::Downcast => output.push_str(&format!(
                "    if let Some(p) = any.downcast_ref::<{rust_type}>() {{ return Some(p.to_wit()); }}\n"
            )),
        }
        return;
    }

    let mut prep_code = String::new();
    let mut field_inits = String::new();
    let mut possible = true;

    if let Fields::Named(fields) = s.fields {
        for field in fields.named {
            if !matches!(field.vis, syn::Visibility::Public(_)) {
                possible = false;
                break;
            }
            let mut field_name = field.ident.as_ref().unwrap().to_string();
            let wit_field = field_name.to_snake_case();
            let (type_ident, is_ref, is_slice) = get_type_info(&field.ty);

            if type_ident == "DynamicRecipe" {
                if mode == MappingMode::Serialize {
                    possible = false;
                } else {
                    possible = false; // Cannot handle DynamicRecipe yet
                }
                continue;
            }

            if field_name == "type" {
                field_name = "r#type".to_string();
            }

            // source that depend on the mode
            let src = match mode {
                MappingMode::Serialize => format!("data.{}", wit_field),
                MappingMode::Deserialize => format!("p.{}", field_name),
                MappingMode::ToWit => format!("self.{}", field_name),
                MappingMode::Downcast => String::new(),
            };

            let (prep, expr, ok) = convert_value(
                &type_ident,
                is_ref,
                is_slice,
                &src,
                Some(&wit_field),
                mode,
                "            ",
            );

            if !ok {
                possible = false;
                break;
            }

            prep_code.push_str(&prep);

            // Pour les structs, on génère "dst: expr,"
            let dst_name = match mode {
                MappingMode::Serialize => field_name.clone(),
                _ => wit_field.clone(),
            };
            field_inits.push_str(&format!("                {}: {},\n", dst_name, expr));
        }
    } else {
        possible = false;
    }

    if possible {
        emit_struct_output(
            output,
            mode,
            state,
            attr_name,
            variant_prefix,
            rust_path_prefix,
            &struct_name,
            &struct_name_with_lt,
            &wit_case,
            &prep_code,
            &field_inits,
        );
    }
}

fn emit_struct_output(
    output: &mut String,
    mode: MappingMode,
    state: &str,
    attr_name: &str,
    variant_prefix: &str,
    rust_path_prefix: &str,
    struct_name: &str,
    struct_name_with_lt: &str,
    wit_case: &str,
    prep_code: &str,
    field_inits: &str,
) {
    let packet_ns = if rust_path_prefix.contains("java") {
        "java_packets"
    } else {
        "bedrock_packets"
    };

    match mode {
        MappingMode::Serialize => {
            output.push_str(&format!(
                "        {}::{}(data){} => {{\n",
                variant_prefix,
                wit_case,
                serialization_guard(state, attr_name)
            ));
            output.push_str(prep_code);
            output.push_str(&format!(
                "            let p = {}::{} {{\n",
                rust_path_prefix, struct_name
            ));
            output.push_str(field_inits);
            output.push_str("            };\n");
            output.push_str("            let mut buf = Vec::new();\n");
            if attr_name == "java_packet" {
                output.push_str("            pumpkin_protocol::java::packet_encoder::write_packet(&p, &version, &mut buf).ok()?;\n");
            } else {
                output.push_str("            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).ok()?;\n");
            }
            if variant_prefix == "ClientboundPacket" {
                output.push_str(&format!(
                    "            Some((<{}::{} as MultiVersionJavaPacket>::state(), buf.into()))\n",
                    rust_path_prefix, struct_name_with_lt
                ));
            } else {
                output.push_str("            Some(buf.into())\n");
            }
            output.push_str("        }\n");
        }
        MappingMode::Deserialize => {
            if rust_path_prefix.contains("java") {
                output.push_str(&format!(
                    "        id if id == {}::{}::to_id(version) => {{\n",
                    rust_path_prefix, struct_name
                ));
                output.push_str("            use pumpkin_protocol::ServerPacket;\n");
                output.push_str(&format!(
                    "            let p = <{}::{} as pumpkin_protocol::ServerPacket>::read(&mut payload, &version).ok()?;\n",
                    rust_path_prefix, struct_name
                ));
                output.push_str("            if !payload.is_empty() { return None; }\n");
            } else {
                output.push_str(&format!(
                    "        id if id == <{}::{} as pumpkin_protocol::Packet>::PACKET_ID as i32 => {{\n",
                    rust_path_prefix, struct_name
                ));
                output.push_str("            use pumpkin_protocol::BServerPacket;\n");
                output.push_str(&format!(
                    "            let p = <{}::{} as pumpkin_protocol::BServerPacket>::read(&mut Cursor::new(payload)).ok()?;\n",
                    rust_path_prefix, struct_name
                ));
            }
            output.push_str(prep_code);
            output.push_str(&format!(
                "            Some({}::{}(crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::{}::{} {{\n",
                variant_prefix, wit_case, packet_ns, wit_case
            ));
            output.push_str(field_inits);
            output.push_str("            }))\n");
            output.push_str("        }\n");
        }
        MappingMode::ToWit => {
            let side = if rust_path_prefix.contains("java") {
                "Java"
            } else {
                "Bedrock"
            };
            let wit_type = if rust_path_prefix.contains("java") {
                "ClientboundPacket"
            } else {
                "BClientboundPacket"
            };
            output.push_str(&format!(
                "impl ToWitClientbound{} for {}::{} {{\n",
                side, rust_path_prefix, struct_name_with_lt
            ));
            output.push_str(&format!("    fn to_wit(&self) -> {} {{\n", wit_type));
            output.push_str(prep_code);
            output.push_str(&format!(
                "        {}::{}(crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::{}::{} {{\n",
                variant_prefix, wit_case, packet_ns, wit_case
            ));
            output.push_str(field_inits);
            output.push_str("        })\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");
        }
        MappingMode::Downcast => {
            output.push_str(&format!(
                "    if let Some(p) = any.downcast_ref::<{}::{}>() {{\n",
                rust_path_prefix, struct_name
            ));
            output.push_str("        return Some(p.to_wit());\n");
            output.push_str("    }\n");
        }
    }
}

fn process_enum(
    e: syn::ItemEnum,
    state: &str,
    output: &mut String,
    attr_name: &str,
    variant_prefix: &str,
    rust_path_prefix: &str,
    mode: MappingMode,
) {
    if !matches!(e.vis, syn::Visibility::Public(_)) {
        return;
    }
    let enum_name = e.ident.to_string();
    let wit_case = if state == "play" {
        enum_name.to_pascal_case()
    } else {
        format!("{}{}", state, enum_name).to_pascal_case()
    };
    let enum_name_with_lt = if !e.generics.params.is_empty() {
        format!("{}<'_>", enum_name)
    } else {
        enum_name.clone()
    };
    let packet_ns = if rust_path_prefix.contains("java") {
        "java_packets"
    } else {
        "bedrock_packets"
    };
    let wit_ns = format!(
        "crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::{}::{}",
        packet_ns, wit_case
    );

    match mode {
        MappingMode::Serialize => {
            output.push_str(&format!(
                "        {}::{}(data){} => {{\n",
                variant_prefix,
                wit_case,
                serialization_guard(state, attr_name)
            ));
            output.push_str("            let p = match data {\n");
            for v in &e.variants {
                if let Some(arm) = generate_serialize_arm(&enum_name, v, rust_path_prefix, &wit_ns)
                {
                    output.push_str(&arm);
                } else {
                    // variant isn't supported
                    return;
                }
            }
            output.push_str("            };\n");
            output.push_str("            let mut buf = Vec::new();\n");
            if attr_name == "java_packet" {
                output.push_str("            pumpkin_protocol::java::packet_encoder::write_packet(&p, &version, &mut buf).ok()?;\n");
            } else {
                output.push_str("            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).ok()?;\n");
            }
            if variant_prefix == "ClientboundPacket" {
                output.push_str(&format!(
                    "            Some((<{}::{} as MultiVersionJavaPacket>::state(), buf.into()))\n",
                    rust_path_prefix, enum_name_with_lt
                ));
            } else {
                output.push_str("            Some(buf.into())\n");
            }
            output.push_str("        }\n");
        }

        MappingMode::Deserialize => {
            if rust_path_prefix.contains("java") {
                output.push_str(&format!(
                    "        id if id == {}::{}::to_id(version) => {{\n",
                    rust_path_prefix, enum_name
                ));
                output.push_str("            use pumpkin_protocol::ServerPacket;\n");
                output.push_str(&format!(
                    "            let p = <{}::{} as pumpkin_protocol::ServerPacket>::read(&mut payload, &version).ok()?;\n",
                    rust_path_prefix, enum_name
                ));
                output.push_str("            if !payload.is_empty() { return None; }\n");
            } else {
                output.push_str(&format!(
                    "        id if id == <{}::{} as pumpkin_protocol::Packet>::PACKET_ID as i32 => {{\n",
                    rust_path_prefix, enum_name
                ));
                output.push_str("            use pumpkin_protocol::BServerPacket;\n");
                output.push_str(&format!(
                    "            let p = <{}::{} as pumpkin_protocol::BServerPacket>::read(&mut Cursor::new(payload)).ok()?;\n",
                    rust_path_prefix, enum_name
                ));
            }
            output.push_str(&format!("            Some(match p {{\n"));
            for v in &e.variants {
                if let Some(arm) = generate_deserialize_arm(
                    &rust_path_prefix,
                    &enum_name,
                    v,
                    variant_prefix,
                    &wit_case,
                    &wit_ns,
                ) {
                    output.push_str(&arm);
                } else {
                    return;
                }
            }
            output.push_str("            })\n");
            output.push_str("        }\n");
        }

        MappingMode::ToWit => {
            let side = if rust_path_prefix.contains("java") {
                "Java"
            } else {
                "Bedrock"
            };
            let wit_type = if rust_path_prefix.contains("java") {
                "ClientboundPacket"
            } else {
                "BClientboundPacket"
            };
            output.push_str(&format!(
                "impl ToWitClientbound{} for {}::{} {{\n",
                side, rust_path_prefix, enum_name_with_lt
            ));
            output.push_str(&format!("    fn to_wit(&self) -> {} {{\n", wit_type));
            output.push_str("        match self {\n");
            for v in &e.variants {
                if let Some(arm) = generate_to_wit_arm(v, variant_prefix, &wit_case, &wit_ns) {
                    output.push_str(&arm);
                } else {
                    return;
                }
            }
            output.push_str("        }\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");
        }

        MappingMode::Downcast => {
            output.push_str(&format!(
                "    if let Some(p) = any.downcast_ref::<{}::{}>() {{\n",
                rust_path_prefix, enum_name
            ));
            output.push_str("        return Some(p.to_wit());\n");
            output.push_str("    }\n");
        }
    }
}

/// return the bindings of a variant : (pattern_destruct, vec of (binding_name, syn::Type))
fn variant_bindings(v: &syn::Variant) -> (String, Vec<(String, syn::Type)>) {
    match &v.fields {
        Fields::Unnamed(fields) => {
            let bindings: Vec<(String, syn::Type)> = fields
                .unnamed
                .iter()
                .map(|f| {
                    let (type_ident, _, _) = get_type_info(&f.ty);
                    (type_ident.to_snake_case(), f.ty.clone())
                })
                .collect();
            let pattern = format!(
                "({})",
                bindings
                    .iter()
                    .map(|(n, _)| n.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            (pattern, bindings)
        }
        Fields::Named(fields) => {
            let bindings: Vec<(String, syn::Type)> = fields
                .named
                .iter()
                .map(|f| {
                    let name = f.ident.as_ref().unwrap().to_string();
                    (name, f.ty.clone())
                })
                .collect();
            let pattern = format!(
                "{{ {} }}",
                bindings
                    .iter()
                    .map(|(n, _)| n.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            (pattern, bindings)
        }
        Fields::Unit => (String::new(), vec![]),
    }
}

/// Serialize : WitEnum::Variant(binding) => RustEnum::Variant(converted)
fn generate_serialize_arm(
    enum_name: &str,
    v: &syn::Variant,
    rust_path_prefix: &str,
    wit_ns: &str,
) -> Option<String> {
    let variant_name = v.ident.to_string();
    let (pattern, bindings) = variant_bindings(v);

    if bindings.is_empty() {
        return Some(format!(
            "                {}::{} => {}::{}::{},\n",
            wit_ns, variant_name, rust_path_prefix, enum_name, variant_name
        ));
    }

    let mut prep = String::new();
    let mut converted = Vec::new();
    for (binding, ty) in &bindings {
        let (type_ident, is_ref, is_slice) = get_type_info(ty);
        let (p, expr, ok) = convert_value(
            &type_ident,
            is_ref,
            is_slice,
            binding,
            Some(binding),
            MappingMode::Serialize,
            "                ",
        );
        if !ok {
            return None;
        }
        prep.push_str(&p);
        converted.push(expr);
    }

    Some(format!(
        "{}                {}::{}{} => {}::{}::{}({}),\n",
        prep,
        wit_ns,
        variant_name,
        pattern,
        rust_path_prefix,
        enum_name,
        variant_name,
        converted.join(", ")
    ))
}

/// Deserialize : RustEnum::Variant(binding) => WitVariantPrefix::WitCase(WitNs::Variant(converted))
fn generate_deserialize_arm(
    rust_path_prefix: &str,
    enum_name: &str,
    v: &syn::Variant,
    variant_prefix: &str,
    wit_case: &str,
    wit_ns: &str,
) -> Option<String> {
    let variant_name = v.ident.to_string();
    let (pattern, bindings) = variant_bindings(v);

    if bindings.is_empty() {
        return Some(format!(
            "                {}::{}::{} => {}::{}({}::{}),\n",
            rust_path_prefix,
            enum_name,
            variant_name,
            variant_prefix,
            wit_case,
            wit_ns,
            variant_name
        ));
    }

    let mut prep = String::new();
    let mut converted = Vec::new();
    for (binding, ty) in &bindings {
        let (type_ident, is_ref, is_slice) = get_type_info(ty);
        let (p, expr, ok) = convert_value(
            &type_ident,
            is_ref,
            is_slice,
            binding,
            Some(binding),
            MappingMode::Deserialize,
            "                ",
        );
        if !ok {
            return None;
        }
        prep.push_str(&p);
        converted.push(expr);
    }

    Some(format!(
        "{}                {}::{}::{}{} => {}::{}({}::{}({})),\n",
        prep,
        rust_path_prefix,
        enum_name,
        variant_name,
        pattern,
        variant_prefix,
        wit_case,
        wit_ns,
        variant_name,
        converted.join(", ")
    ))
}

/// ToWit : RustEnum::Variant(binding) => WitVariantPrefix::WitCase(WitNs::Variant(converted))
fn generate_to_wit_arm(
    v: &syn::Variant,
    variant_prefix: &str,
    wit_case: &str,
    wit_ns: &str,
) -> Option<String> {
    let variant_name = v.ident.to_string();
    let (pattern, bindings) = variant_bindings(v);

    if bindings.is_empty() {
        return Some(format!(
            "            Self::{} => {}::{}({}::{}),\n",
            variant_name, variant_prefix, wit_case, wit_ns, variant_name
        ));
    }

    let mut prep = String::new();
    let mut converted = Vec::new();
    for (binding, ty) in &bindings {
        let (type_ident, is_ref, is_slice) = get_type_info(ty);
        let (p, expr, ok) = convert_value(
            &type_ident,
            is_ref,
            is_slice,
            binding,
            Some(binding),
            MappingMode::ToWit,
            "            ",
        );
        if !ok {
            return None;
        }
        prep.push_str(&p);
        converted.push(expr);
    }

    Some(format!(
        "{}            Self::{}{} => {}::{}({}::{}({})),\n",
        prep,
        variant_name,
        pattern,
        variant_prefix,
        wit_case,
        wit_ns,
        variant_name,
        converted.join(", ")
    ))
}
