[package]
name = "pumpkin-inventory"
version.workspace = true
edition.workspace = true

[dependencies]
# For items
pumpkin-world = { path = "../pumpkin-world" }

log.workspace = true

num-traits = "0.2"
num-derive = "0.4"
thiserror = "1.0.63"
itertools.workspace = true
crossbeam.workspace = true
tokio.workspace = true
