interface context {
    use server.{server};
    use event.{event-priority};

    resource context {
        register-event: func(handler-id: u32, event-priority: event-priority, blocking: bool);
        get-server: func() -> server;
    }
}
