/// Entity system for Pumpkin plugins.
///
/// This interface provides access to block entities and other entity types
/// that can be manipulated by plugins.
///
/// # Block Entities
///
/// Block entities are blocks with additional data beyond their state:
/// - Chests (inventory contents)
/// - Furnaces (burn time, cook time, inventory)
/// - Command blocks (stored command, output)
/// - Signs (text lines)
/// - And more...
interface entity {
    use %world.{entity};
}
