interface player {
    use common.{position, game-mode};
    use %world.{%world};
    use text.{text-component};

    resource player {
        get-id: func () -> result<string, string>;
        get-name: func () -> result<string, string>;

        // Basic state
        get-position: func () -> result<position, string>;
        get-rotation: func () -> result<tuple<f32, f32>, string>;
        get-world: func () -> result<%world, string>;
        get-gamemode: func () -> result<game-mode, string>;
        set-gamemode: func (mode: game-mode) -> result<bool, string>;

        // Messaging & titles
        send-system-message: func (text: text-component, overlay: bool) -> result<_, string>;
        show-title: func (text: text-component) -> result<_, string>;
        show-subtitle: func (text: text-component) -> result<_, string>;
        show-actionbar: func (text: text-component) -> result<_, string>;
        send-title-animation: func (fade-in: s32, stay: s32, fade-out: s32) -> result<_, string>;

        // Teleport & kick
        teleport: func (position: position, yaw: f32, pitch: f32) -> result<_, string>;
        teleport-world: func (world-ref: %world, position: position, yaw: option<f32>, pitch: option<f32>) -> result<_, string>;
        kick: func (message: text-component) -> result<_, string>;
    }
}
