package pumpkin:plugin;

world plugin {
    use context.{context};
    use event.{event};
    use server.{server as server-instance};

    // This is what the host should provide to the plugin
    import logging;
    import server;
    import context;

    // This is what the plugin should provide
    export init-plugin: func();
    export on-load: func(context: context) -> result<_, string>;
    export on-unload: func(context: context) -> result<_, string>;
    export metadata;
    export common;
    export handle-event: func(event-id: u32, server: server-instance, event: event) -> event;
}
