interface server {
    enum difficulty {
        peaceful,
        easy,
        normal,
        hard,
    }

    resource server {
        get-difficulty: func() -> difficulty;
        set-difficulty: func(difficulty: difficulty);
        get-motd: func() -> string;
        set-motd: func(motd: string);
    }
}
