[package]
name = "pumpkin-datapack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Minecraft datapack loading and management for Pumpkin"

[dependencies]
pumpkin-data.workspace = true
pumpkin-protocol.workspace = true
pumpkin-util.workspace = true
pumpkin-registry.workspace = true

serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true
rand.workspace = true
zip = { version = "2.4", default-features = false, features = ["deflate"] }

[lints]
workspace = true
