[package]
name = "pumpkin-world"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-nbt = { path = "../pumpkin-nbt" }
pumpkin-util = { path = "../pumpkin-util" }
pumpkin-config = { path = "../pumpkin-config" }
pumpkin-macros = { path = "../pumpkin-macros" }
pumpkin-data = { path = "../pumpkin-data" }

bytes.workspace = true


tokio.workspace = true
rayon.workspace = true
derive_more.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true

num-derive = "0.4"

dashmap = "6.1"

num-traits = "0.2"

# Compression   
flate2 = "1.0"
lz4 = "1.28"

file-guard = "0.2"
indexmap = "2.7"

enum_dispatch = "0.3"

fastnbt = { git = "https://github.com/owengage/fastnbt.git" }

noise = "0.9"
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "chunk_noise"
harness = false

[[bench]]
name = "chunk_noise_populate"
harness = false
