[package]
name = "pumpkin-config"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-util = { path = "../pumpkin-util" }
serde.workspace = true
log.workspace = true
uuid.workspace = true

# So we don't read/write to disk when testing
tempdir = "0.3.7"

toml = "0.8"
