//! Full packet id table generated by Pumpkin.
//!
//! This mirrors the server's packet id table for all supported versions.

#[allow(clippy::all)]
#[allow(dead_code)]
mod generated {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../pumpkin-data/src/generated/packet.rs"
    ));
}

pub use generated::*;
