use crate::random::RandomImpl;
#[cfg(feature = "codegen")]
use proc_macro2::{Span, TokenStream};
#[cfg(feature = "codegen")]
use quote::{ToTokens, quote};
use serde::Deserialize;
#[cfg(feature = "codegen")]
use syn::LitInt;

/// Represents different types of number providers that generate integer values.
#[derive(Deserialize, Clone, Debug)]
#[serde(tag = "type")]
pub enum NormalIntProvider {
    /// Always returns the same constant value.
    #[serde(rename = "minecraft:constant")]
    Constant(ConstantIntProvider),
    /// Returns uniformly distributed random values within an inclusive range [min, max].
    #[serde(rename = "minecraft:uniform")]
    Uniform(UniformIntProvider),
    /// Returns values biased toward the lower end of the range (triangular distribution).
    #[serde(rename = "minecraft:biased_to_bottom")]
    BiasedToBottom(BiasedToBottomIntProvider),
    /// Returns values very biased toward the lower end of the range.
    #[serde(rename = "minecraft:very_biased_to_bottom")]
    VeryBiasedToBottom(VeryBiasedToBottomIntProvider),
    /// Wraps another provider and clamps its output to a specified range.
    #[serde(rename = "minecraft:clamped")]
    Clamped(ClampedIntProvider),
    #[serde(rename = "minecraft:trapezoid")]
    Trapezoid(TrapezoidIntProvider),
    /// Returns values from a normal (Gaussian) distribution, clamped to a specified inclusive range.
    #[serde(rename = "minecraft:clamped_normal")]
    ClampedNormal(ClampedNormalIntProvider),
    /// Returns values from a weighted list where entries have different probabilities.
    #[serde(rename = "minecraft:weighted_list")]
    WeightedList(WeightedListIntProvider),
}

#[cfg(feature = "codegen")]
impl ToTokens for NormalIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        match self {
            Self::Constant(constant) => {
                tokens.extend(quote! {
                    NormalIntProvider::Constant(#constant)
                });
            }
            Self::Uniform(uniform) => {
                tokens.extend(quote! {
                    NormalIntProvider::Uniform(#uniform)
                });
            }
            Self::BiasedToBottom(biased) => {
                tokens.extend(quote! {
                    NormalIntProvider::BiasedToBottom(#biased)
                });
            }
            Self::VeryBiasedToBottom(very_biased) => {
                tokens.extend(quote! {
                    NormalIntProvider::VeryBiasedToBottom(#very_biased)
                });
            }
            Self::Clamped(clamped) => {
                tokens.extend(quote! {
                    NormalIntProvider::Clamped(#clamped)
                });
            }
            Self::ClampedNormal(clamped_normal) => {
                tokens.extend(quote! {
                    NormalIntProvider::ClampedNormal(#clamped_normal)
                });
            }
            Self::Trapezoid(trapezoid) => {
                tokens.extend(quote! {
                    NormalIntProvider::Trapezoid(#trapezoid)
                });
            }
            Self::WeightedList(weighted_list) => {
                tokens.extend(quote! {
                    NormalIntProvider::WeightedList(#weighted_list)
                });
            }
        }
    }
}

/// A flexible integer provider that can be either a constant value or a complex provider.
#[derive(Deserialize, Clone, Debug)]
#[serde(untagged)]
pub enum IntProvider {
    /// A complex provider with configurable distribution.
    Object(NormalIntProvider),
    /// A simple constant integer value.
    Constant(i32),
}

#[cfg(feature = "codegen")]
impl ToTokens for IntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        match self {
            Self::Object(int_provider) => {
                tokens.extend(quote! {
                    IntProvider::Object(#int_provider)
                });
            }
            Self::Constant(i) => tokens.extend(quote! {
                IntProvider::Constant(#i)
            }),
        }
    }
}

impl IntProvider {
    /// Returns the minimum possible value this provider can generate.
    ///
    /// # Returns
    /// The minimum value (inclusive) that can be generated by this provider.
    #[must_use]
    pub fn get_min(&self) -> i32 {
        match self {
            Self::Object(int_provider) => match int_provider {
                NormalIntProvider::Constant(constant) => constant.get_min(),
                NormalIntProvider::Uniform(uniform) => uniform.get_min(),
                NormalIntProvider::BiasedToBottom(biased) => biased.get_min(),
                NormalIntProvider::VeryBiasedToBottom(very_biased) => very_biased.get_min(),
                NormalIntProvider::Clamped(clamped) => clamped.get_min(),
                NormalIntProvider::Trapezoid(trapezoid) => trapezoid.get_min(),
                NormalIntProvider::ClampedNormal(clamped_normal) => clamped_normal.get_min(),
                NormalIntProvider::WeightedList(weighted_list) => weighted_list.get_min(),
            },
            Self::Constant(i) => *i,
        }
    }

    /// Generates a random integer value using the configured distribution.
    ///
    /// # Arguments
    /// - `random` – The random number generator to use.
    ///
    /// # Returns
    /// A random integer value according to the provider's distribution strategy.
    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        match self {
            Self::Object(int_provider) => match int_provider {
                NormalIntProvider::Constant(constant) => constant.get(random),
                NormalIntProvider::Uniform(uniform) => uniform.get(random),
                NormalIntProvider::BiasedToBottom(biased) => biased.get(random),
                NormalIntProvider::VeryBiasedToBottom(very_biased) => very_biased.get(random),
                NormalIntProvider::Clamped(clamped) => clamped.get(random),
                NormalIntProvider::ClampedNormal(clamped_normal) => clamped_normal.get(random),
                NormalIntProvider::WeightedList(weighted_list) => weighted_list.get(random),
                NormalIntProvider::Trapezoid(trapezoid_int_provider) => {
                    trapezoid_int_provider.get(random)
                }
            },
            Self::Constant(i) => *i,
        }
    }

    /// Returns the maximum possible value this provider can generate.
    ///
    /// # Returns
    /// The maximum value (inclusive) that can be generated by this provider.
    #[must_use]
    pub fn get_max(&self) -> i32 {
        match self {
            Self::Object(int_provider) => match int_provider {
                NormalIntProvider::Constant(constant) => constant.get_max(),
                NormalIntProvider::Uniform(uniform) => uniform.get_max(),
                NormalIntProvider::BiasedToBottom(biased) => biased.get_max(),
                NormalIntProvider::VeryBiasedToBottom(very_biased) => very_biased.get_max(),
                NormalIntProvider::Clamped(clamped) => clamped.get_max(),
                NormalIntProvider::ClampedNormal(clamped_normal) => clamped_normal.get_max(),
                NormalIntProvider::WeightedList(weighted_list) => weighted_list.get_max(),
                NormalIntProvider::Trapezoid(trapezoid_int_provider) => {
                    trapezoid_int_provider.get_max()
                }
            },
            Self::Constant(i) => *i,
        }
    }
}

/// An integer provider that always returns the same constant value.
#[derive(Deserialize, Clone, Debug)]
pub struct ConstantIntProvider {
    /// The constant value that will always be returned.
    pub value: i32,
}

#[cfg(feature = "codegen")]
impl ToTokens for ConstantIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let value = LitInt::new(&self.value.to_string(), Span::call_site());
        tokens.extend(quote! {
            ConstantIntProvider { value: #value }
        });
    }
}

impl ConstantIntProvider {
    /// Creates a new constant provider with the given value.
    ///
    /// # Arguments
    /// - `value` – The constant value to return.
    ///
    /// # Returns
    /// A new `ConstantIntProvider` instance.
    #[must_use]
    pub const fn new(value: i32) -> Self {
        Self { value }
    }

    /// Returns the minimum value (same as the constant value).
    ///
    /// # Returns
    /// The constant value.
    #[must_use]
    pub const fn get_min(&self) -> i32 {
        self.value
    }

    /// Returns the constant value, ignoring the random number generator.
    ///
    /// # Arguments
    /// - `_random` – The random number generator (unused).
    ///
    /// # Returns
    /// The constant value.
    pub const fn get(&self, _random: &mut impl RandomImpl) -> i32 {
        self.value
    }

    /// Returns the maximum value (same as the constant value).
    ///
    /// # Returns
    /// The constant value.
    #[must_use]
    pub const fn get_max(&self) -> i32 {
        self.value
    }
}

/// An integer provider that generates values biased toward the lower end of the range.
#[derive(Deserialize, Clone, Debug)]
pub struct BiasedToBottomIntProvider {
    /// The minimum value (inclusive) that can be generated.
    pub min_inclusive: i32,
    /// The maximum value (inclusive) that can be generated.
    pub max_inclusive: i32,
}

#[cfg(feature = "codegen")]
impl ToTokens for BiasedToBottomIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let min_inclusive = LitInt::new(&self.min_inclusive.to_string(), Span::call_site());
        let max_inclusive = LitInt::new(&self.max_inclusive.to_string(), Span::call_site());
        tokens.extend(quote! {
            BiasedToBottomIntProvider { min_inclusive: #min_inclusive, max_inclusive: #max_inclusive }
        });
    }
}

impl BiasedToBottomIntProvider {
    /// Creates a new biased-to-bottom provider with the specified range.
    ///
    /// # Arguments
    /// - `min_inclusive` – The minimum value (inclusive).
    /// - `max_inclusive` – The maximum value (inclusive).
    ///
    /// # Returns
    /// A new `BiasedToBottomIntProvider` instance.
    #[must_use]
    pub const fn new(min_inclusive: i32, max_inclusive: i32) -> Self {
        Self {
            min_inclusive,
            max_inclusive,
        }
    }

    /// Returns the minimum inclusive value.
    ///
    /// # Returns
    /// The minimum value that can be generated (inclusive).
    #[must_use]
    pub const fn get_min(&self) -> i32 {
        self.min_inclusive
    }

    /// Generates a random value biased toward the lower end of the range.
    ///
    /// # Arguments
    /// - `random` – The random number generator to use.
    ///
    /// # Returns
    /// A random integer in the range [`min_inclusive`, `max_inclusive`], with lower values more likely.
    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        if self.min_inclusive >= self.max_inclusive {
            return self.min_inclusive;
        }
        let range = self.max_inclusive - self.min_inclusive + 1;
        let bound = random.next_bounded_i32(range) + 1;
        self.min_inclusive + random.next_bounded_i32(bound)
    }

    /// Returns the maximum inclusive value.
    ///
    /// # Returns
    /// The maximum value that can be generated (inclusive).
    #[must_use]
    pub const fn get_max(&self) -> i32 {
        self.max_inclusive
    }
}

/// An integer provider that generates values very biased toward the lower end of the range.
#[derive(Deserialize, Clone, Debug)]
pub struct VeryBiasedToBottomIntProvider {
    /// The minimum value (inclusive) that can be generated.
    pub min_inclusive: i32,
    /// The maximum value (inclusive) that can be generated.
    pub max_inclusive: i32,
    /// The number of additional random bounds steps (default 1).
    #[serde(default = "default_very_biased_inner")]
    pub inner: i32,
}

const fn default_very_biased_inner() -> i32 {
    1
}

#[cfg(feature = "codegen")]
impl ToTokens for VeryBiasedToBottomIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let min_inclusive = LitInt::new(&self.min_inclusive.to_string(), Span::call_site());
        let max_inclusive = LitInt::new(&self.max_inclusive.to_string(), Span::call_site());
        let inner = LitInt::new(&self.inner.to_string(), Span::call_site());
        tokens.extend(quote! {
            VeryBiasedToBottomIntProvider {
                min_inclusive: #min_inclusive,
                max_inclusive: #max_inclusive,
                inner: #inner,
            }
        });
    }
}

impl VeryBiasedToBottomIntProvider {
    #[must_use]
    pub const fn new(min_inclusive: i32, max_inclusive: i32, inner: i32) -> Self {
        Self {
            min_inclusive,
            max_inclusive,
            inner,
        }
    }

    #[must_use]
    pub const fn get_min(&self) -> i32 {
        self.min_inclusive
    }

    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        if self.min_inclusive >= self.max_inclusive {
            return self.min_inclusive;
        }
        let range = self.max_inclusive - self.min_inclusive + 1;
        let mut bound = range;
        for _ in 0..=self.inner {
            bound = random.next_bounded_i32(bound) + 1;
        }
        self.min_inclusive + bound - 1
    }

    #[must_use]
    pub const fn get_max(&self) -> i32 {
        self.max_inclusive
    }
}

/// An integer provider that wraps another provider and clamps its output.
#[derive(Deserialize, Clone, Debug)]
pub struct ClampedIntProvider {
    /// The source provider to get values from.
    pub source: Box<IntProvider>,
    /// The minimum value (inclusive) to clamp to.
    pub min_inclusive: i32,
    /// The maximum value (inclusive) to clamp to.
    pub max_inclusive: i32,
}

#[cfg(feature = "codegen")]
impl ToTokens for ClampedIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let source = &self.source;
        let min_inclusive = LitInt::new(&self.min_inclusive.to_string(), Span::call_site());
        let max_inclusive = LitInt::new(&self.max_inclusive.to_string(), Span::call_site());
        tokens.extend(quote! {
            ClampedIntProvider {
                source: Box::new(#source),
                min_inclusive: #min_inclusive,
                max_inclusive: #max_inclusive
            }
        });
    }
}

impl ClampedIntProvider {
    /// Creates a new clamped provider with the specified source and range.
    ///
    /// # Arguments
    /// - `source` – The source provider to get values from.
    /// - `min_inclusive` – The minimum value (inclusive) to clamp to.
    /// - `max_inclusive` – The maximum value (inclusive) to clamp to.
    ///
    /// # Returns
    /// A new `ClampedIntProvider` instance.
    #[must_use]
    pub fn new(source: IntProvider, min_inclusive: i32, max_inclusive: i32) -> Self {
        Self {
            source: Box::new(source),
            min_inclusive,
            max_inclusive,
        }
    }

    /// Returns the minimum value after clamping.
    ///
    /// # Returns
    /// The larger of the source's minimum and the clamp minimum.
    #[must_use]
    pub fn get_min(&self) -> i32 {
        self.min_inclusive.max(self.source.get_min())
    }

    /// Generates a random value from the source and clamps it to the configured range.
    ///
    /// # Arguments
    /// - `random` – The random number generator to use.
    ///
    /// # Returns
    /// A random integer from the source provider, clamped to [`min_inclusive`, `max_inclusive`].
    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        self.source
            .get(random)
            .clamp(self.min_inclusive, self.max_inclusive)
    }

    /// Returns the maximum value after clamping.
    ///
    /// # Returns
    /// The smaller of the source's maximum and the clamp maximum.
    #[must_use]
    pub fn get_max(&self) -> i32 {
        self.max_inclusive.min(self.source.get_max())
    }
}

#[derive(Deserialize, Clone, Debug)]
pub struct TrapezoidIntProvider {
    /// The minimum value (inclusive) to clamp to.
    pub min_inclusive: i32,
    /// The maximum value (inclusive) to clamp to.
    pub max_inclusive: i32,
    pub plateau: i32,
}

#[cfg(feature = "codegen")]
impl ToTokens for TrapezoidIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let min_inclusive = LitInt::new(&self.min_inclusive.to_string(), Span::call_site());
        let max_inclusive = LitInt::new(&self.max_inclusive.to_string(), Span::call_site());
        let plateau = LitInt::new(&self.plateau.to_string(), Span::call_site());
        tokens.extend(quote! {
            TrapezoidIntProvider {
                min_inclusive: #min_inclusive,
                max_inclusive: #max_inclusive,
                plateau: #plateau
            }
        });
    }
}

impl TrapezoidIntProvider {
    /// Creates a new clamped provider with the specified source and range.
    ///
    /// # Arguments
    /// - `min_inclusive` – The minimum value (inclusive) to clamp to.
    /// - `max_inclusive` – The maximum value (inclusive) to clamp to.
    ///
    /// # Returns
    /// A new `ClampedIntProvider` instance.
    #[must_use]
    pub const fn new(min_inclusive: i32, max_inclusive: i32, plateau: i32) -> Self {
        Self {
            min_inclusive,
            max_inclusive,
            plateau,
        }
    }

    /// Returns the minimum value after clamping.
    ///
    /// # Returns
    /// The larger of the source's minimum and the clamp minimum.
    #[must_use]
    pub const fn get_min(&self) -> i32 {
        self.min_inclusive
    }

    /// Generates a random value from the source and clamps it to the configured range.
    ///
    /// # Arguments
    /// - `random` – The random number generator to use.
    ///
    /// # Returns
    /// A random integer from the source provider, clamped to [`min_inclusive`, `max_inclusive`].
    ///
    /// Mirrors vanilla `TrapezoidInt.sample` draw for draw:
    ///
    /// ```java
    /// if (this.plateau == 0 && this.maxInclusive == -this.minInclusive) {
    ///     return random.nextInt(this.maxInclusive + 1) - random.nextInt(this.maxInclusive + 1);
    /// }
    /// int range = this.maxInclusive - this.minInclusive;
    /// if (this.plateau == range) {
    ///     return Mth.randomBetweenInclusive(random, this.minInclusive, this.maxInclusive);
    /// }
    /// int half = (range - this.plateau) / 2;
    /// int rest = range - half;
    /// return this.minInclusive
    ///     + Mth.randomBetweenInclusive(random, 0, rest)
    ///     + Mth.randomBetweenInclusive(random, 0, half);
    /// ```
    ///
    /// The symmetric branch is the one every `random_offset` placement modifier in the 26.2
    /// data takes, and it is a *difference* of two draws, not a sum offset by `min`.
    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        if self.plateau == 0 && self.max_inclusive == -self.min_inclusive {
            return random.next_bounded_i32(self.max_inclusive + 1)
                - random.next_bounded_i32(self.max_inclusive + 1);
        }
        let range = self.max_inclusive - self.min_inclusive;
        if self.plateau == range {
            return self.min_inclusive + random.next_bounded_i32(range + 1);
        }
        let half = (range - self.plateau) / 2;
        let rest = range - half;
        self.min_inclusive + random.next_bounded_i32(rest + 1) + random.next_bounded_i32(half + 1)
    }

    /// Returns the maximum value after clamping.
    ///
    /// # Returns
    /// The smaller of the source's maximum and the clamp maximum.
    #[must_use]
    pub const fn get_max(&self) -> i32 {
        self.max_inclusive
    }
}

/// An integer provider that generates values from a clamped normal distribution.
#[derive(Deserialize, Clone, Debug)]
pub struct ClampedNormalIntProvider {
    /// The mean (centre) of the normal distribution.
    pub mean: f32,
    /// The standard deviation of the normal distribution.
    pub deviation: f32,
    /// The minimum inclusive clamp value.
    pub min_inclusive: i32,
    /// The maximum inclusive clamp value.
    pub max_inclusive: i32,
}

#[cfg(feature = "codegen")]
impl ToTokens for ClampedNormalIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let mean = syn::LitFloat::new(&self.mean.to_string(), Span::call_site());
        let deviation = syn::LitFloat::new(&self.deviation.to_string(), Span::call_site());
        let min_inclusive = LitInt::new(&self.min_inclusive.to_string(), Span::call_site());
        let max_inclusive = LitInt::new(&self.max_inclusive.to_string(), Span::call_site());
        tokens.extend(quote! {
            ClampedNormalIntProvider {
                mean: #mean,
                deviation: #deviation,
                min_inclusive: #min_inclusive,
                max_inclusive: #max_inclusive
            }
        });
    }
}

impl ClampedNormalIntProvider {
    /// Creates a new clamped normal provider with the specified parameters.
    ///
    /// # Arguments
    /// - `mean` – The mean (centre) of the normal distribution.
    /// - `deviation` – The standard deviation of the normal distribution.
    /// - `min_inclusive` – The minimum inclusive clamp value.
    /// - `max_inclusive` – The maximum inclusive clamp value.
    ///
    /// # Returns
    /// A new `ClampedNormalIntProvider` instance.
    #[must_use]
    pub const fn new(mean: f32, deviation: f32, min_inclusive: i32, max_inclusive: i32) -> Self {
        Self {
            mean,
            deviation,
            min_inclusive,
            max_inclusive,
        }
    }

    /// Returns the minimum inclusive clamp value.
    ///
    /// # Returns
    /// The minimum value that can be generated after clamping.
    #[must_use]
    pub const fn get_min(&self) -> i32 {
        self.min_inclusive
    }

    /// Generates a random value from the clamped normal distribution.
    ///
    /// # Arguments
    /// - `random` – The random number generator to use.
    ///
    /// # Returns
    /// A random integer from a normal distribution, rounded and clamped to [`min_inclusive`, `max_inclusive`].
    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        // NOTE: Generate a normal distribution value and clamp to range
        let gaussian = random.next_gaussian() as f32;
        let value = gaussian.mul_add(self.deviation, self.mean).round() as i32;
        value.clamp(self.min_inclusive, self.max_inclusive)
    }

    /// Returns the maximum inclusive clamp value.
    ///
    /// # Returns
    /// The maximum value that can be generated after clamping.
    #[must_use]
    pub const fn get_max(&self) -> i32 {
        self.max_inclusive
    }
}

/// A weighted entry in a weighted list provider.
#[derive(Deserialize, Clone, Debug)]
pub struct WeightedEntry {
    /// The integer provider that generates the value for this entry.
    pub data: IntProvider,
    /// The weight (probability) of this entry being chosen.
    pub weight: i32,
}

#[cfg(feature = "codegen")]
impl ToTokens for WeightedEntry {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let data = &self.data;
        let weight = LitInt::new(&self.weight.to_string(), Span::call_site());
        tokens.extend(quote! {
            WeightedEntry { data: #data, weight: #weight }
        });
    }
}

/// An integer provider that selects values from a weighted list.
#[derive(Deserialize, Clone, Debug)]
pub struct WeightedListIntProvider {
    /// The list of weighted entries to choose from.
    pub distribution: Vec<WeightedEntry>,
}

#[cfg(feature = "codegen")]
impl ToTokens for WeightedListIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let distribution = &self.distribution;
        tokens.extend(quote! {
            WeightedListIntProvider { distribution: vec![#(#distribution),*] }
        });
    }
}

impl WeightedListIntProvider {
    /// Creates a new weighted list provider with the given distribution.
    ///
    /// # Arguments
    /// - `distribution` – The list of weighted entries.
    ///
    /// # Returns
    /// A new `WeightedListIntProvider` instance.
    #[must_use]
    pub const fn new(distribution: Vec<WeightedEntry>) -> Self {
        Self { distribution }
    }

    /// Returns the minimum possible value from all entries.
    ///
    /// # Returns
    /// The smallest minimum value among all entries, or 0 if the list is empty.
    #[must_use]
    pub fn get_min(&self) -> i32 {
        self.distribution
            .iter()
            .map(|entry| entry.data.get_min())
            .min()
            .unwrap_or(0)
    }

    /// Selects a random entry based on weights and generates a value from it.
    ///
    /// # Arguments
    /// - `random` – The random number generator to use.
    ///
    /// # Returns
    /// A random integer from the chosen weighted entry, or 0 if the list is empty.
    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        if self.distribution.is_empty() {
            return 0;
        }

        // Calculate total weight.
        let total_weight: i32 = self.distribution.iter().map(|entry| entry.weight).sum();

        if total_weight == 0 {
            return 0;
        }

        // Choose a random weight.
        let chosen_weight = random.next_bounded_i32(total_weight);
        let mut current_weight = 0;

        // Find the entry corresponding to the chosen weight.
        for entry in &self.distribution {
            current_weight += entry.weight;
            if chosen_weight < current_weight {
                return entry.data.get(random);
            }
        }

        // Fallback to the last entry.
        self.distribution
            .last()
            .map_or(0, |entry| entry.data.get(random))
    }

    /// Returns the maximum possible value from all entries.
    ///
    /// # Returns
    /// The largest maximum value among all entries, or 0 if the list is empty.
    #[must_use]
    pub fn get_max(&self) -> i32 {
        self.distribution
            .iter()
            .map(|entry| entry.data.get_max())
            .max()
            .unwrap_or(0)
    }
}

/// An integer provider that generates uniformly distributed random values.
#[derive(Deserialize, Clone, Debug)]
pub struct UniformIntProvider {
    /// The minimum value (inclusive) that can be generated.
    pub min_inclusive: i32,
    /// The maximum value (inclusive) that can be generated.
    pub max_inclusive: i32,
}

#[cfg(feature = "codegen")]
impl ToTokens for UniformIntProvider {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let min_inclusive = LitInt::new(&self.min_inclusive.to_string(), Span::call_site());
        let max_inclusive = LitInt::new(&self.max_inclusive.to_string(), Span::call_site());

        tokens.extend(quote! {
            UniformIntProvider { min_inclusive: #min_inclusive, max_inclusive: #max_inclusive }
        });
    }
}

impl UniformIntProvider {
    /// Creates a new uniform provider with the specified inclusive range.
    ///
    /// # Arguments
    /// - `min_inclusive` – The minimum value (inclusive).
    /// - `max_inclusive` – The maximum value (inclusive).
    ///
    /// # Returns
    /// A new `UniformIntProvider` instance.
    #[must_use]
    pub const fn new(min_inclusive: i32, max_inclusive: i32) -> Self {
        Self {
            min_inclusive,
            max_inclusive,
        }
    }

    /// Returns the minimum inclusive value.
    ///
    /// # Returns
    /// The minimum value that can be generated (inclusive).
    #[must_use]
    pub const fn get_min(&self) -> i32 {
        self.min_inclusive
    }

    /// Generates a uniformly distributed random value in the configured range.
    ///
    /// # Arguments
    /// - `random` – The random number generator to use.
    ///
    /// # Returns
    /// A random integer in the inclusive range [`min_inclusive`, `max_inclusive`].
    pub fn get(&self, random: &mut impl RandomImpl) -> i32 {
        random.next_inbetween_i32(self.min_inclusive, self.max_inclusive)
    }

    /// Returns the maximum inclusive value.
    ///
    /// # Returns
    /// The maximum value that can be generated (inclusive).
    #[must_use]
    pub const fn get_max(&self) -> i32 {
        self.max_inclusive
    }
}

/// Tests for the integer provider implementations.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::random::{RandomGenerator, get_seed};

    #[test]
    fn constant_int_provider() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );
        let provider = ConstantIntProvider::new(42);

        assert_eq!(provider.get_min(), 42);
        assert_eq!(provider.get_max(), 42);
        assert_eq!(provider.get(&mut random), 42);
        assert_eq!(provider.get(&mut random), 42); // Should always return the same value
    }

    #[test]
    fn uniform_int_provider() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );
        let provider = UniformIntProvider::new(1, 10);

        assert_eq!(provider.get_min(), 1);
        assert_eq!(provider.get_max(), 10);

        // Test that values are within range
        for _ in 0..100 {
            let value = provider.get(&mut random);
            assert!(
                (1..=10).contains(&value),
                "Value {value} is outside range [1, 10]"
            );
        }
    }

    #[test]
    fn biased_to_bottom_int_provider() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );
        let provider = BiasedToBottomIntProvider::new(1, 20);

        assert_eq!(provider.get_min(), 1);
        assert_eq!(provider.get_max(), 20);

        // Test that values are within range (biased toward lower values)
        for _ in 0..100 {
            let value = provider.get(&mut random);
            assert!(
                (1..=20).contains(&value),
                "Value {value} is outside range [1, 20]"
            );
        }
    }

    #[test]
    fn clamped_normal_int_provider() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );
        let provider = ClampedNormalIntProvider::new(5.0, 2.0, 1, 10);

        assert_eq!(provider.get_min(), 1);
        assert_eq!(provider.get_max(), 10);

        // Test that values are within range
        for _ in 0..100 {
            let value = provider.get(&mut random);
            assert!(
                (1..=10).contains(&value),
                "Value {value} is outside range [1, 10]"
            );
        }
    }

    #[test]
    fn clamped_int_provider() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );
        let source =
            IntProvider::Object(NormalIntProvider::Uniform(UniformIntProvider::new(1, 100)));
        let provider = ClampedIntProvider::new(source, 5, 15);

        assert_eq!(provider.get_min(), 5);
        assert_eq!(provider.get_max(), 15);

        // Test that values are within a clamped range.
        for _ in 0..100 {
            let value = provider.get(&mut random);
            assert!(
                (5..=15).contains(&value),
                "Value {value} is outside clamped range [5, 15]"
            );
        }
    }

    #[test]
    fn weighted_list_int_provider() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );

        let entries = vec![
            WeightedEntry {
                data: IntProvider::Constant(1),
                weight: 10,
            },
            WeightedEntry {
                data: IntProvider::Constant(2),
                weight: 20,
            },
            WeightedEntry {
                data: IntProvider::Constant(3),
                weight: 5,
            },
        ];

        let provider = WeightedListIntProvider::new(entries);

        assert_eq!(provider.get_min(), 1);
        assert_eq!(provider.get_max(), 3);

        // Test that values are from the weighted list
        for _ in 0..100 {
            let value = provider.get(&mut random);
            assert!(
                (1..=3).contains(&value),
                "Value {value} is not from the weighted list"
            );
        }
    }

    #[test]
    fn int_provider_enum_constant() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );
        let provider = IntProvider::Constant(25);

        assert_eq!(provider.get_min(), 25);
        assert_eq!(provider.get_max(), 25);
        assert_eq!(provider.get(&mut random), 25);
    }

    #[test]
    fn int_provider_enum_object() {
        let mut random = RandomGenerator::Xoroshiro(
            crate::random::xoroshiro128::Xoroshiro::from_seed(get_seed()),
        );
        let uniform = UniformIntProvider::new(5, 15);
        let provider = IntProvider::Object(NormalIntProvider::Uniform(uniform));

        assert_eq!(provider.get_min(), 5);
        assert_eq!(provider.get_max(), 15);

        let value = provider.get(&mut random);
        assert!(
            (5..=15).contains(&value),
            "Value {value} is outside range [5, 15]"
        );
    }

    /// Reference values taken from the real 26.2 server jar:
    /// `TrapezoidInt.of(min, max, plateau).sample(new LegacyRandomSource(13579))`, eight
    /// samples per provider, and the same with a `XoroshiroRandomSource(13579)`.
    #[test]
    fn trapezoid_int_matches_vanilla_samples() {
        /// `(min, max, plateau)` plus the eight `LegacyRandomSource(13579)` samples and the
        /// eight `XoroshiroRandomSource(13579)` samples vanilla returns for it.
        type TrapezoidCase = (i32, i32, i32, [i32; 8], [i32; 8]);

        let cases: &[TrapezoidCase] = &[
            // Every `random_offset` placement modifier in the 26.2 data is symmetric with
            // plateau 0, i.e. `nextInt(max + 1) - nextInt(max + 1)`.
            (
                -7,
                7,
                0,
                [0, -5, 1, -4, 0, -7, -4, 3],
                [-2, -6, -1, -7, 2, 0, 0, -3],
            ),
            (
                -6,
                6,
                0,
                [3, 2, 3, -4, 1, -2, 6, 1],
                [-2, -5, -1, -6, 2, 0, 1, -2],
            ),
            (
                -3,
                3,
                0,
                [0, -2, 1, -2, 0, -3, -2, 1],
                [-1, -3, 0, -3, 1, 0, 0, -1],
            ),
            (
                -2,
                2,
                0,
                [0, -1, 0, -1, 0, -1, 1, -1],
                [0, -2, -1, -2, 1, 0, 0, -1],
            ),
            // `patch_sugar_cane*` uses a `[0, 0]` y_spread: still two draws, always zero.
            (0, 0, 0, [0; 8], [0; 8]),
            // The general branch: `min + nextInt(rest + 1) + nextInt(half + 1)`.
            (
                -3,
                5,
                2,
                [3, 3, -2, 0, 4, 0, 1, 0],
                [1, 0, 2, 0, -1, 3, 5, 3],
            ),
            // `plateau == range`: a single uniform draw.
            (2, 5, 3, [3, 3, 2, 4, 4, 3, 2, 4], [3, 4, 2, 5, 4, 4, 2, 5]),
        ];

        for (min, max, plateau, legacy_expected, xoroshiro_expected) in cases {
            let provider = TrapezoidIntProvider::new(*min, *max, *plateau);

            let mut legacy = crate::random::legacy_rand::LegacyRand::from_seed(13579);
            let legacy_actual: [i32; 8] = std::array::from_fn(|_| provider.get(&mut legacy));
            assert_eq!(
                &legacy_actual, legacy_expected,
                "legacy samples for trapezoid({min}, {max}, {plateau})"
            );

            let mut xoroshiro = crate::random::xoroshiro128::Xoroshiro::from_seed(13579);
            let xoroshiro_actual: [i32; 8] = std::array::from_fn(|_| provider.get(&mut xoroshiro));
            assert_eq!(
                &xoroshiro_actual, xoroshiro_expected,
                "xoroshiro samples for trapezoid({min}, {max}, {plateau})"
            );
        }
    }

    /// A `[0, 0]` trapezoid consumes two draws in vanilla, not zero: after one
    /// `sample(new LegacyRandomSource(13579))` the next `nextInt()` is 392090517, the *third*
    /// value of that stream (`1265370827, 1234256338, 392090517, ...`). Skipping those draws
    /// desynchronises every later draw of the feature.
    #[test]
    fn trapezoid_int_empty_range_still_consumes_two_draws() {
        let mut random = crate::random::legacy_rand::LegacyRand::from_seed(13579);
        assert_eq!(TrapezoidIntProvider::new(0, 0, 0).get(&mut random), 0);
        assert_eq!(random.next_i32(), 392090517);

        // `plateau == range` consumes exactly one draw.
        let mut random = crate::random::legacy_rand::LegacyRand::from_seed(13579);
        TrapezoidIntProvider::new(2, 5, 3).get(&mut random);
        assert_eq!(random.next_i32(), 1234256338);
    }
}
